Match User itasii-deploy
    ChrootDirectory /var/www/itasii
    ForceCommand internal-sftp -d /public -u 0022
    AuthorizedKeysFile /etc/ssh/authorized_keys/%u
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    DisableForwarding yes
    PermitTunnel no
    PermitTTY no
    PermitUserRC no
Match all
